/* INVESTORS */
export const GET_INVESTORS = "GET_INVESTORS"
export const GET_INVESTORS_SUCCESS = "GET_INVESTORS_SUCCESS"
export const GET_INVESTORS_FAIL = "GET_INVESTORS_FAIL"

/* PROJECTS DETAIL*/
export const GET_INVESTOR_DETAIL = "GET_INVESTOR_DETAIL"
export const GET_INVESTOR_DETAIL_SUCCESS = "GET_INVESTOR_DETAIL_SUCCESS"
export const GET_INVESTOR_DETAIL_FAIL = "GET_INVESTOR_DETAIL_FAIL"

